### ISSUE TITLE
Setting multiple ethreum rpc is not working from docker-compose

### ISSUE THREAD

**Issue by leonprou** [graphprotocol/graph-node#1328]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I cannot connect to multiple networks while running graph-node in docker-compose

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In docker-compose I set the following:
```
    environment:
      postgres_host: postgres:5432
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'fuse:rpc.fusenet.io ropsten:https://ropsten.infura.io/v3/{key}'
      RUST_LOG: info
```
Then graph-node log gives the error:
```
graph-node_1  | Oct 31 13:52:44.953 INFO Creating transport, url: rpc.fusenet.io ropsten:https://ropsten.infura.io/v3/{key}, network: fuse
graph-node_1  | Oct 31 13:52:44.959 INFO Successfully connected to IPFS node at: http://ipfs:5001/
graph-node_1  | thread 'main' panicked at 'Failed to connect to Ethereum RPC: Transport("RelativeUrlWithoutBase")', src/libcore/result.rs:1084:5
```

**What is the expected behavior?**
as @Jannis told me it should work
