### ISSUE TITLE
Block handlers affect block scanning too early

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#1395]
When you have two data sources (or more) in a subgraph, one with an earlier start block and one with a later start block and a block handler, like below:

```yaml
dataSources:
  - source:
      startBlock: 1
      mapping:
        eventHandlers:
          ...
  - source:
      startBlock: 100
      mapping:
        blockHandlers:
          - handler: handleBlock
```

then the block scanning takes the block handler into account for blocks `#1` - `#99` already. This slows indexing of historic blocks down significantly. This is because we take the minimum start block of all data sources and then scan blocks taking _all_ filters into account. We never call `handleBlock` for blocks `#1` - `#99` though, so the indexing execution is correct.

A more efficient block scanning algorithm would divide the block scanning into ranges where different filters apply. In the above case, this would be:

- `skip` blocks `[#0]`
- `scan` blocks #1 - #99 with just the filters from the first data source
- `scan` blocks #100 onward with the filters from both data sources
