### ISSUE TITLE
CallHandler: Doesn't work for function with tuple arguments

### ISSUE THREAD

**Issue by samparsky** [graphprotocol/graph-node#1668]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
CallHanlders doesn't work with tuple arguments. A call handler for a function with tuple arguments doesn't get invoked

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```js
contract Test {
  struct Check {
     uint param;
  }
  function test(Check memory check) {
    
  }
}
```

`subgraph.yaml`

```yml
specVersion: 0.0.2
description: AdEx Protocol subgraph
schema:
  file: ./schema.graphql

dataSources:
  ...
  callHandlers:
        - function: test(tuple)
          handler: handleTest
```

The `handleTest` handler doesn't ever get invoked

**What is the expected behavior?**

The handleTest handler should get invoked

**Comment by Jannis** [comment]
Tuples are represented as tuples of their field types, e.g. `(uint256,bytes32)`, so (assuming it's supposed to be `uint param`, not `unit param`), the manifest should look as follows:
```yaml
callHandlers:
  - function: test((uint256))
    handler: handleTest
```
