### ISSUE TITLE
SubgraphSyncingFailure Error

### ISSUE THREAD

**Issue by simibac** [graphprotocol/graph-node#1983]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Error: `Subgraph instance failed to run: Mapping terminated before handling trigger: oneshot canceled, code: SubgraphSyncingFailure, id: QmfQUt4WWBiMSPG4fEGFSRosi8cdBZxgCwLUzXwYjBZVgS`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I use the factory pattern to create a new contract. 

```
contract Factory{
    event NewVenue(address contractAddress);

    function createVenue(){
        Venue newVenue = new Venue();
        emit NewVenue(address(newVenue))
    }
}

contract Venue{
    event VenueCreated(address owner);
    uint data;
    constructor(uint data){
        this.data = data;
        emit VenueCreated(msg.sender);
    }
}
```

For my graph setup, I use templates:

```yaml
specVersion: 0.0.2
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: Factory
    network: rinkeby
    source:
      address: "0x055b6e305864DC13E0b9F4ecB1591eE2e8a99C99"
      abi: Factory
      startBlock: 7442159
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.4
      language: wasm/assemblyscript
      entities:
        - VenueCreated
      abis:
        - name: Factory
          file: ./abis/Factory.json
      eventHandlers:
        - event: NewVenue(address)
          handler: handleNewVenue
      file: ./src/factoryMapping.ts
templates:
  - name: VenueContract
    kind: ethereum/contract
    network: rinkeby
    source:
      abi: VenueContract
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.1
      language: wasm/assemblyscript
      file: ./src/venueMapping.ts
      entities:
        - Venue
      abis:
        - name: VenueContract
          file: ./abis/VenueContract.json
      eventHandlers:
        - event: VenueCreated(address)
          handler: handleVenueCreated
```
The `factoryMapping.js` creates a new data source as described in the docs:

```js
export function handleNewVenue(e: NewVenue): void {
  VenueContract.create(e.params.contractAddress);
  let venue = new Venue(e.address.toHex())
  venue.save()
}
```

but the error occurs in the `venueMapping.ts`:

```js
export function handleVenueCreated(e: VenueCreated): void {
  log.info("address " + e.address.toHex(), [])

  let venue = Venue.load(e.address.toHex()) //ERROR HERE
  
  let venueContract = VenueContract.bind(e.address);
  
  venue.data = venueContract.data();
  venue.owner = e.params.owner();
  venue.save();
}
```

How do I need to load the venue given the `VenueCreated`? `e.address.toHex()` returns the correct address but it somehow fails to load the entity.

**What is the expected behavior?**
Setting the data in the `handleVenueCreated` function. I know I could theoretically emit `data` in the `NewVenue` event, but my contract is more complex and I dont want to emit everything as an event. I want to be able to read it from the contract variable.
