### ISSUE TITLE
Feature Request: Support indexed argument filtering

### ISSUE THREAD

**Issue by dekz** [graphprotocol/graph-node#2052]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently TheGraph pulls all logs matching the specified `topic0`. In certain cases, specifically ours, we do not need to process every event, but a subset of these events. 

For example, picture a subgraph which wishes to process a subset of Uniswap `Swap` events which only pertain to their dApp. There are many `Swap` events in almost every block, though not all of these are relevant to the dApp.

We would like to make use of the additional topics to specify the additional `indexed` fields, allowing us to skip over events which do not relate to our dApp. This would significantly save on syncing time and reduce excess processing by nodes.

Currently we are restricted to the following:

```yaml
          eventHandlers:
              - event: Swap(indexed address,uint256,uint256,uint256,uint256,indexed address)
                handler: handleGenericSwap
```

We would like the ability to add additional filtering to the declaration:

**Single exact filter**

```yaml
          eventHandlers:
              - event: Swap(indexed address,uint256,uint256,uint256,uint256,indexed address)
                topic1: "0xabcd...." # filter only events where the sender is the 0xabcd address
                handler: handleSwap
```

**Or filter on the first indexed argument** 
```yaml
          eventHandlers:
              - event: Swap(indexed address,uint256,uint256,uint256,uint256,indexed address)
                topic1: ["0xabcd....", "0x1234"] # filter only events where the sender is the 0xabcd or "0x1234" address
                handler: handleSwap
```

**Or filter on the second indexed argument** 
```yaml
          eventHandlers:
              - event: Swap(indexed address,uint256,uint256,uint256,uint256,indexed address)
                topic2: ["0xabcd....", "0x1234"] # filter only events where the recipient is the 0xabcd or "0x1234" address
                handler: handleSwap
```

I'll leave a reference to how an ethereum node is supposed to respect the `topics` argument in the RPC request.

```
A transaction with a log with topics [A, B] will be matched by the following topic filters:
  [] “anything”
  [A] “A in first position (and anything after)”
  [null, B] “anything in first position AND B in second position (and anything after)”
  [A, B] “A in first position AND B in second position (and anything after)”
  [[A, B], [A, B]] “(A OR B) in first position AND (A OR B) in second position (and anything after)”
```

This change would allow us to sync our subgraph much quicker and reduce the overhead of processing unrelated (to our purposes) events. As an example, it currently takes us a solid 24 hours to process our subgraph and as a result we only store approximately 100,000 entities.
