### ISSUE TITLE
[Bug] [Docker] error: The argument '--postgres-url <URL>' cannot be used with '--config <config>'

### ISSUE THREAD

**Issue by schmidsi** [graphprotocol/graph-node#2271]
# Summary

Running `docker-compose up` on my local machine throws the following error from the graph-node:

`graph-node_1  | error: The argument '--postgres-url <URL>' cannot be used with '--config <config>'`

The `graph-node_1` container exits.

# Reproduction
Following these instructions: https://thegraph.com/docs/quick-start#2.-run-a-local-graph-node

```bash
git clone https://github.com/graphprotocol/graph-node/
cd graph-node/docker
```
Changing the `ethereum` environment var to infura mainnet
- `ethereum: 'mainnet:https://mainnet.infura.io/v3/MY_NOT_SO_SECRET_PROJECT_ID'`

```bash
docker-compose up
```

# Expected behaviour

The graph-node container successfully boots and is accessible from the outside.

# Further information

- MacOS Catalina 10.15.7 (19H114)
- Docker Desktop Version 3.1.0
- Docker Engine Version 20.10.2
- Docker Compose Version 1.27.4

**Comment by schmidsi** [comment]
I was able to fix it simply by changing the docker-compose.yml file to not point to the latest image, but to the last version:

```yml
version: '3'
services:
  graph-node:
    # Instead of image: graphprotocol/graph-node
    image: graphprotocol/graph-node:v0.22.0
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:https://mainnet.infura.io/v3/MY_NOT_SO_SECRET_PROJECT_ID'
      RUST_LOG: info
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
```

I was also able to reproduce the behaviour by building the graph-node docker image locally on the master branch.
