### ISSUE TITLE
block handler filters not working: handleBlockWithCallToContract

### ISSUE THREAD

**Issue by qbig** [graphprotocol/graph-node#2314]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
      blockHandlers:
        - handler: handleBlock
        - handler: handleBlockWithCallToContract
          filter:
            kind: call     

`handleBlockWithCallToContract` never got called
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
just deploy subgraph with block handlers
```
      blockHandlers:
        - handler: handleBlock
        - handler: handleBlockWithCallToContract
          filter:
            kind: call     

```
**What is the expected behavior?**
`handleBlock` get called for all blocks while `handleBlockWithCallToContract` only get called when the block contains txs to the contract.

**Comment by azf20** [comment]
Hi! Looking at this - just to verify, the problem here is that the second blockhandler isn't run, rather than that blockhandlers with call filters are not working?

**Comment by waylonflinn** [comment]
I'm experiencing the same problem with only a single block handler defined. When the block handler definition includes the call filter it appears to never be run.

Here is the relevant snippet from my `subgraph.yaml` file.
```yaml
      blockHandlers:
        - handler: handleBlock
          filter:
            kind: call
```

Removing the call filter will cause the handler to be run. Adding the call filter again will cause the handler to not be run.

I would say this means blockhandlers with call filters are not working.
