### ISSUE TITLE
Trouble running the local node with docker? Help/support request.

### ISSUE THREAD

**Issue by vyzaldysanchez** [graphprotocol/graph-node#2321]
**Do you want to request a *feature* or report a *bug*?**
Not really sure if it is a bug, but I'm trying to get some help/support into running a local node with the docker setup, as stated in [the docs](https://thegraph.com/docs/quick-start#local-development).

**What is the current behavior?**
When running `docker-compose up` after running the `./setup.sh` script in Linux I'm getting the following:

![Screenshot from 2021-03-29 17-46-01](https://user-images.githubusercontent.com/8971713/112904761-6dc56500-90b7-11eb-986c-05de03e4d04c.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
As stated previously, just cloning the repo, running the `setup` script for Linux, and then starting the containers. (Note that I already have ganache running)

Here's the `docker-compose.yml` content:

```yml
version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: *****
      postgres_pass: *****
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:http://172.21.0.1:8545'
      RUST_LOG: info
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
```

**What is the expected behavior?**
The graph node should be running without issues locally (?).

Thanks in advance for the support,
