### ISSUE TITLE
[question/feature request] 1 graph-node for several blockchains?

### ISSUE THREAD

**Issue by paulvi** [graphprotocol/graph-node#2603]
**Do you want to request a *feature* or report a *bug*?**
This is [question/feature request] 

**What is the current behavior?**

From https://github.com/graphprotocol/graph-node/blob/master/docs/getting-started.md
```
cargo run -p graph-node --release -- \
  --postgres-url postgresql://<USERNAME><:PASSWORD>@localhost:5432/<POSTGRES_DB_NAME> \
  --ethereum-rpc <ETHEREUM_NETWORK_NAME>:https://mainnet.infura.io \
  --ipfs 127.0.0.1:5001 \
  --debug
```  
Does it mean that only 1 network per graph-node is supported?  

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

Several blockchain could be specified in a list, e.g.

  `--ethereum-rpc mainnet:https://mainnet.infura.io,rinkeby:https://eth-rinkeby.alchemyapi.io/v2/${alchemyApiKey}
  
 
 Also on https://stackoverflow.com/questions/68190257/thegraph-one-graph-node-for-several-blockchains

**Comment by schmidsi** [comment]
@paulvi, this is documented here: https://github.com/graphprotocol/graph-node/blob/master/docs/config.md#configuring-ethereum-providers

**Comment by ZhangAiRen** [comment]
Ia there an example for such file?

Please extend /docs/config.md

**Comment by schmidsi** [comment]
The following lines, directly copy/pasted from the /docs/config.md, is an example:

```toml
[chains]
ingestor = "block_ingestor_node"
[chains.mainnet]
shard = "vip"
provider = [
  { label = "mainnet1", url = "http://..", features = [], headers = { Authorization = "Bearer foo" } },
  { label = "mainnet2", url = "http://..", features = [ "archive", "traces" ] }
]
[chains.kovan]
shard = "primary"
provider = [ { label = "kovan", url = "http://..", features = [] } ]
```

So what's missing?
