### ISSUE TITLE
ERRO ... subgraph `XYZ` has already processed block `22557049`; there are most likely two (or more) nodes indexing this subgraph, code: SubgraphSyncingFailure

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [graphprotocol/graph-node#3074]
Graph-node version:
`v0.25.0` (docker image: `graphprotocol/graph-node:v0.25.0`)

I'm not sure if it's a bug or misconfiguration.

Here's the log output:
```
Dec 15 15:16:01.146 ERRO Subgraph instance failed to run: Error while processing block stream for a subgraph: subgraph `QmUHDd1Gye7vHTEJjwZ3ENzuQdYUnxppSYWf9PyTL4VLpe` has already processed block `22557049`; there are most likely two (or more) nodes indexing this subgraph, code: SubgraphSyncingFailure, sgd: 2, subgraph_id: QmUHDd1Gye7vHTEJjwZ3ENzuQdYUnxppSYWf9PyTL4VLpe, component: SubgraphInstanceManager
```

It happens when I run more than one of `graph-node` processes (kubernetes pods).

If set a different `node_id` env for each process (pod) (valueFrom fieldRef metadata.uid) then preexisting subgraphs/deployments seem to disappear and I can't deploy any new subgraph

**Comment by enzojavier-desimone** [comment]
I am facing the same issue but it happen when a unique `graph-node` is running and the process is interrupted (closed), when running it again the error is displayed and stop to sync

**Comment by azf20** [comment]
Hi @pwilczynskiclearcode - subgraphs can only be assigned to one index node at time, as processing is a linear process. It is possible to connect multiple index nodes to the same database.

@enzojavier-desimone I am not sure what is happening, you are saying you see that error with one subgraph when you restart? What version of graph-node are you using?

**Comment by enzojavier-desimone** [comment]
@azf20 in my case I am able to reproduce it, I am using the `master` branch from this repo, I am running the docker container for `ipfs` and `postgres` with the following `docker-compose.yml`

```
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
``` 

As I am executing the graph-node in a M1 processor the docker container throw error after a time, then I run it in local with the following command

```
cargo run -p graph-node --release -- \
  --postgres-url postgresql://graph-node:let-me-in@localhost:5432/graph-node \
  --ethereum-rpc mainnet:archive,trace:https://mainnet.infura.io/v3/key \
  --ipfs 127.0.0.1:5001
```

Additionally I set the following undocumented env variable `GRAPH_ALLOW_NON_DETERMINISTIC_IPFS` to `true` 

After the graph-node is running, I clone the `master` branch of the (ENS subgraph)[https://github.com/ensdomains/ens-subgraph] and deploy it with `npm run setup`

All is fine and it start to index, but whenI am able to already query the subgraph data, if the `graph-node` is terminated and executed again, I got that error.

I tried defining a `node id` manually, but same issue
