### ISSUE TITLE
Initialization handlers

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#3221]
Subgraph developers often want to initialise a specific state for their subgraph.

Currently this needs to be done across handlers, or on the basis of some other trigger.

TBD: could parts of this use case be handled declaratively in the manifest e.g. via context?

**Comment by azf20** [comment]
This was proposed separately in the Forum: https://forum.thegraph.com/t/grp-0001-decorator-hooks-cron-jobs-and-initialisation-handlers/3347

**Comment by azf20** [comment]
This could be a `type` of block handler, similar to #959:

```
blockHandlers
  - handler: initializeState
    filter:
      kind: once
```
