### ISSUE TITLE
thread 'main' panicked at 'Failed to connect to Ethereum RPC: Transport("RelativeUrlWithoutBase")', chain/ethereum/src/transport.rs:45:14

### ISSUE THREAD

**Issue by shubhank-saxena** [graphprotocol/graph-node#3327]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I have a local ethereum node (get) running and serving RPC link at http://localhost:30303. After mentioning the correct value in docker-compose file, I am facing the error.
docker-compose file :
```
version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      RUST_BACKTRACE: full
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:0.0.0.0:30303'
      GRAPH_LOG: info
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
```
docker-compose error:
```
graph-node_1  | thread 'main' panicked at 'Failed to connect to Ethereum RPC: Transport("RelativeUrlWithoutBase")', chain/ethereum/src/transport.rs:45:14
graph-node_1  | stack backtrace:
graph-node_1  |    0:     0x55981ade0c1c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he3555b48e7dfe7f0
graph-node_1  |    1:     0x55981ae0525c - core::fmt::write::h513b07ca38f4fb1b
graph-node_1  |    2:     0x55981add9125 - std::io::Write::write_fmt::haf8c932b52111354
graph-node_1  |    3:     0x55981ade2840 - std::panicking::default_hook::{{closure}}::hb2e38ec0d91046a3
graph-node_1  |    4:     0x55981ade23f5 - std::panicking::default_hook::h60284635b0ad54a8
graph-node_1  |    5:     0x55981ade2ef4 - std::panicking::rust_panic_with_hook::ha677a669fb275654
graph-node_1  |    6:     0x55981ade29d0 - std::panicking::begin_panic_handler::{{closure}}::h976246fb95d93c31
graph-node_1  |    7:     0x55981ade10c4 - std::sys_common::backtrace::__rust_end_short_backtrace::h38077ee5b7b9f99a
graph-node_1  |    8:     0x55981ade2939 - rust_begin_unwind
graph-node_1  |    9:     0x5598194f3901 - core::panicking::panic_fmt::h35f3a62252ba0fd2
graph-node_1  |   10:     0x5598194f39f3 - core::result::unwrap_failed::hb53671404b9e33c2
graph-node_1  |   11:     0x559819ed511a - graph_chain_ethereum::transport::Transport::new_rpc::h1a634ebb2841e873
graph-node_1  |   12:     0x559819859d7e - graph_node::main::{{closure}}::h3ad3392e8eb46ad2
graph-node_1  |   13:     0x559819820458 - tokio::park::thread::CachedParkThread::block_on::h2b6bfe6fba3c2dde
graph-node_1  |   14:     0x55981966af7d - tokio::runtime::thread_pool::ThreadPool::block_on::h359d6e4e76b46a94
graph-node_1  |   15:     0x55981982185a - tokio::runtime::Runtime::block_on::h3128bf75ee8ade2f
graph-node_1  |   16:     0x5598196a017e - graph_node::main::h9e8c42cf380421f2
graph-node_1  |   17:     0x559819584e43 - std::sys_common::backtrace::__rust_begin_short_backtrace::h226065c14d4d8703
graph-node_1  |   18:     0x5598197f0359 - std::rt::lang_start::{{closure}}::h1a63ad14d7227e32
graph-node_1  |   19:     0x55981ade08ab - std::rt::lang_start_internal::hc4dd8cd3ec4518c2
graph-node_1  |   20:     0x5598196a0348 - main
graph-node_1  |   21:     0x7fc3d764d09b - __libc_start_main
graph-node_1  |   22:     0x5598194f40aa - _start
graph-node_1  |   23:                0x0 - <unknown>
```
