### ISSUE TITLE
try_ fails to trap revert

### ISSUE THREAD

**Issue by habdelra** [graphprotocol/graph-node#3487]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
We are using version 0.26.0 of the graph node in the gnosis chain network. We have a mapping that performs an `eth_call` using the `try_` form of a contract function so that we can trap reverts. However, we are seeing that a revert fails to be trapped by the `try_` function and the subgraph indexing gets stuck in a loop trying to index the event, reporting an error each time, which looks like this:
```
graph-node_1  | Apr 21 18:08:30.338 INFO Performing eth_call: safe.try_getOwners() for safe address 0x3af12EcC0A8Ef31cc935E0B25ea445249207d21A, data_source: Gnosis_v1_3, block_hash: 0x915e38c125b6ffe1c263d5e26bb91a4157106da8ca29228a419bedd8693afaf7, block_number: 21735473, sgd: 1, subgraph_id: QmbmJ6MYUNFEq1KMFUfkSCfKvM5gW6fwko2R7uKDENJwpW, component: SubgraphInstanceManager
graph-node_1  | Apr 21 18:42:30.521 WARN Trying again after eth_call RPC call for block #21735473 (915e38c125b6ffe1c263d5e26bb91a4157106da8ca29228a419bedd8693afaf7) failed (attempt #10) with result Err(Web3Error(Rpc(Error { code: ServerError(-32015), message: "VM execution error.", data: Some(String("revert")) }))), block_hash: 0x915e38c125b6ffe1c263d5e26bb91a4157106da8ca29228a419bedd8693afaf7, block_number: 21735473, sgd: 1, subgraph_id: QmcB3wMGzvqjJDtvZW5VDQmUwZH2RRyYdtojTQVMW5n9qy, component: SubgraphInstanceManager
graph-node_1  | Apr 21 18:42:30.535 INFO Done processing trigger, gas_used: 0, data_source: Gnosis_v1_3, handler: handleProxyCreation, total_ms: 1565, transaction: 0xbd72…6d83, address: 0xa6b7…6ab2, signature: ProxyCreation(address,address), block_hash: 0x915e38c125b6ffe1c263d5e26bb91a4157106da8ca29228a419bedd8693afaf7, block_number: 21735473, sgd: 1, subgraph_id: QmcB3wMGzvqjJDtvZW5VDQmUwZH2RRyYdtojTQVMW5n9qy, component: SubgraphInstanceManager
graph-node_1  | Apr 21 18:42:30.537 INFO Possible reorg detected, retrying, error: failed to process trigger: block #21735473 (0x915e…faf7), transaction bd72451723d4a9cc3a039db3501ac105b3eba0f1deb4d4efb9ffd7c3408b6d83: Ethereum node returned an error when calling function "getOwners" of contract "GnosisSafe": RPC error: Error { code: ServerError(-32015), message: "VM execution error.", data: Some(String("revert")) }
graph-node_1  | wasm backtrace:
graph-node_1  |     0: 0x240b - <unknown>!~lib/@graphprotocol/graph-ts/index/TypedMap<~lib/string/String,~lib/@graphprotocol/graph-ts/index/Value>#get
graph-node_1  |     1: 0x2607 - <unknown>!src/mappings/gnosis-proxy-factory_v1_3/handleProxyCreation
graph-node_1  |     2: 0x2708 - <unknown>!~lib/internal/memory/memcmp
graph-node_1  | , block_hash: 0x915e38c125b6ffe1c263d5e26bb91a4157106da8ca29228a419bedd8693afaf7, block_number: 21735473, sgd: 1, subgraph_id: QmcB3wMGzvqjJDtvZW5VDQmUwZH2RRyYdtojTQVMW5n9qy, component: SubgraphInstanceManager
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The revert can be see in the gnosis chain (aka xdai). 

Specifically we have a mapper that looks like this:
```ts
import { ProxyCreation } from '../../generated/Gnosis_v1_3/GnosisProxyFactory_v1_3';
import { processGnosisProxyEvent } from './gnosis-proxy-factory';

export function handleProxyCreation(event: ProxyCreation): void {
  processGnosisProxyEvent(event.params.proxy, event, '1.3');
}
```
which wraps this module:

```ts
import { GnosisSafe } from '../../generated/Gnosis_v1_3/GnosisSafe';
import { GnosisSafe as GnosisSafeTemplate } from '../../generated/templates';
import { Safe, SafeOwner } from '../../generated/schema';
import { toChecksumAddress, makeAccount } from '../utils';
import { Address, ethereum, log } from '@graphprotocol/graph-ts';

export function processGnosisProxyEvent(proxyAddress: Address, event: ethereum.Event, gnosisVer: string): void {
  let safeAddress = toChecksumAddress(proxyAddress);

  let safeEntity = new Safe(safeAddress);
  safeEntity.createdAt = event.block.timestamp;

  let safe = GnosisSafe.bind(proxyAddress);
  log.info('Performing eth_call: safe.try_getOwners() for safe address {}', [safeAddress]);
  let ownersResult = safe.try_getOwners();
  if (ownersResult.reverted) {
    log.error('Failed to get owners for safe {}', [safeAddress]);
    return;
  }
  let owners = ownersResult.value;

  for (let i = 0; i < owners.length; i++) {
    let ownerAddress = toChecksumAddress(owners[i]);
    makeAccount(ownerAddress);

    let safeOwnerId = safeAddress + '-' + ownerAddress;
    let safeOwnerEntity = new SafeOwner(safeOwnerId);
    safeOwnerEntity.owner = ownerAddress;
    safeOwnerEntity.safe = safeAddress;
    safeOwnerEntity.createdAt = event.block.timestamp;
    safeOwnerEntity.ownershipChangedAt = event.block.timestamp;
    safeOwnerEntity.save();
  }
  safeEntity.save();
  log.debug('created gnosis v{} safe entity {}', [gnosisVer, safeAddress]);

  GnosisSafeTemplate.create(proxyAddress);
}

```
Whose data source looks like this:
```yml
  - kind: ethereum/contract
    name: Gnosis_v1_3
    network: xdai
    source:
      address: "0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2"
      abi: GnosisProxyFactory_v1_3
      startBlock: 21735463
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.4
      language: wasm/assemblyscript
      entities:
        - Safe
        - Account
        - SafeOwner
      abis:
        - name: GnosisProxyFactory_v1_3
          file: ./abis/GnosisProxyFactory_v1_3.json
        - name: GnosisSafe
          file: ./abis/GnosisSafe.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
      eventHandlers:
        - event: ProxyCreation(address,address)
          handler: handleProxyCreation
      file: ./src/mappings/gnosis-proxy-factory_v1_3.ts
```
The ABI for the GnosisProxyFactory_v1_3 which is emitting the events that the mapper is processing is available here: https://blockscout.com/xdai/mainnet/address/0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2/contracts
The ABI for the GnosisSafe contract which is the contract that we are performing an eth_call that is reverting is available here: https://blockscout.com/xdai/mainnet/address/0x3E5c63644E683549055b9Be8653de26E0B4CD36E/contracts

Using some logging, we've found that this line specifically triggers the error:
```ts
 let ownersResult = safe.try_getOwners();
```
Using a gnosis chain archive node you can see the revert here: (`0x14BA831` is the block this event was emitted `21735473`)
```
POST https://xdai-archive-df.xdaichain.com/
{
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [{
      "to": "0x3af12EcC0A8Ef31cc935E0B25ea445249207d21A",
      "data": "0xa0e67e2b"
    }, "0x14BA831"],
    "id": 1
```
this has the response of
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32015,
        "message": "VM execution error.",
        "data": "Reverted 0x"
    },
    "id": 1
}
```

(incidentally we are following up in a separate thread with the Gnosis Safe team on why this particular call reverts here https://ethereum.stackexchange.com/questions/126648/call-reverts-when-asking-a-safe-for-its-owners-gnosis-chain)

**What is the expected behavior?**
My expectation would be that the call:
```ts
 let ownersResult = safe.try_getOwners();
```
would actually absorb the revert without error, and that `ownersResult.reverted` would be equal to `true`.
