### ISSUE TITLE
Question - What is the proper way to set an environment variable when running as docker-compose?

### ISSUE THREAD

**Issue by wup-one** [graphprotocol/graph-node#3592]
What is the proper way to set an environment variable when running a graph-node through docker-compose?

For example, is this supposed to work if I'm looing to define GRAPH_GRAPHQL_MAX_DEPTH as 100?

docker-compose.yml:

```                                                           
version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    environment:
      GRAPH_GRAPHQL_MAX_DEPTH: 100
```

I've been struggling with getting various environment variables working, and I'm just not sure if they're getting passed through fine or not.

Thanks
