### ISSUE TITLE
Dynamic data sources for NEAR accounts

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#3628]
NEAR subgraphs currently don't support dynamic data sources. A simpler alternative to dynamic data-sources that is possible for NEAR is string-matching of NEAR accounts, which are human readable
e.g. good-morning.near

Often situations involving dynamic data sources on NEAR involve sub-accounts, e.g. [nft.nearapps.near](https://explorer.near.org/accounts/nft.nearapps.near). Instead of full dynamic data sources, we could support string matching on NEAR account names

```
dataSources:
  - kind: near
    network: near-mainnet
    source:
      accounts: good-morning.near # accounts not account will monitor all accounts matching this string, including sub-accounts
      startBlock: 10662188 # Required for NEAR
```

Receipt handlers would continue to work as they do today.

 * This would require a new specVersion. *

**Comment by mangas** [comment]
In terms of spec I think the following could make sense:

The existing use case
```
dataSources:
  - kind: near
    network: near-mainnet
    source:
      account: good-morning.near 
      startBlock: 10662188 # Required for NEAR
```

The new spec:

Support for single account AND filters
```
dataSources:
  - kind: near
    network: near-mainnet
    source:
      # accounts prefix and suffix can be be used to produce an AND filter on account names
      # this would match the example "good-morning.near"
      # oneof prefix or suffix need to be provided. Empty would be an invalid 
      accounts: 
         prefix: good # Optional if suffix present
         suffix: morning.near # Optional if prefix is present
      startBlock: 10662188 # Required for NEAR
```

Matching multiple accounts (still discussing this with stephane but I think this maybe too complicated for what we need?)
```
dataSources:
  - kind: near
    network: near-mainnet
    source:
      # accounts prefix and suffix can be be used to produce an AND filter on account names
      # this would match the example "good-morning.near" "bad-morning.near" "good-evening.near" and "bad-mirning.near"
      # oneof prefix or suffix need to be provided. Empty would be an invalid 
      accounts: 
         prefix: # Optional if suffix present and has at least 1 entry
            - good 
            - bad
         suffix: # Optional if prefix is present and has at least 1 entry
            - morning.near 
            - evening.near 
      startBlock: 10662188 # Required for NEAR
```
