### ISSUE TITLE
Request Feature: subgraph with tenderly mainnet fork

### ISSUE THREAD

**Issue by timPrachasri** [graphprotocol/graph-node#4006]
## This is a feature request

Subgraph cannot track events coming from tenderly mainnet fork

## Background
Background: Since I use tenderly's mainnet fork as a way to make sure that my contract works in the mainnet-identical environment as much as possible, having subgraph able to source events from mainnetfork can be very beneficial to some dev fellows including me

## Reference(s)
https://docs.tenderly.co/simulations-and-forks/how-to-create-a-fork

**Comment by azf20** [comment]
hey @timPrachasri - have you tried indexing using a tenderly mainnet fork rpc? Do you see errors / unexpected behaviours?

**Comment by eladmallel** [comment]
hey @azf20, how would you connect your subgraph to an RPC endpoint?
I am reading the subgraph manifest spec here and not seeing the option to do so:
https://github.com/graphprotocol/graph-node/blob/master/docs/subgraph-manifest.md#15-data-source

**Comment by azf20** [comment]
Hi @eladmallel - the rpc endpoint is configured in the Graph Node configuration https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml#L22

**Comment by eladmallel** [comment]
> Hi @eladmallel - the rpc endpoint is configured in the Graph Node configuration https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml#L22

thanks! so IIUC not something one can expect to get from the hosted service right?

the way to use this would be to host our own node?

**Comment by azf20** [comment]
yes that is correct, the Hosted Service has its own network configuration

**Comment by azf20** [comment]
hi @timPrachasri. I have taken a look into this, and successfully used a mainnet fork with a local subgraph. One slight gotcha is the reorg threshold used by the Graph Node. The default threshold is 250 blocks, and it fetches every receipt for every block. Testing this locally, this takes quite a long time to fetch the receipts, and can encounter rate limits on rpc. The reorg threshold isn't needed for this local testing, so this can be addressed by setting the `ETHEREUM_REORG_THRESHOLD` environment variable to 1 so only one block worth of receipts is fetched.
i.e. in a docker compose:
```
    environment:
      ETHEREUM_REORG_THRESHOLD: 1
```
This then only fetches one block, after which the subgraph indexes as expected.
Closing this given the above, but please re-open if you are still having issues getting events from a forked RPC

**Comment by skyao2002** [comment]
I am running a local graph node indexing a tenderly rpc. I am repeatedly getting this error:

```
WARN Unexpected RPC error, error:  Transport(Code(400)),
```

Here is my docker-compose.yml

```
version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - 172.23.0.1:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:https://rpc.tenderly.co/fork/53fea442-6f5a-4c23-9a03-918f0db9c824'
      GRAPH_LOG: info
      ETHEREUM_REORG_THRESHOLD: 1
      ETHEREUM_ANCESTOR_COUNT: 1
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
```
