### ISSUE TITLE
Rules-based system to control index creation and similar attributes

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#4325]
There are a few things that can be set manually through `graphman` or directly by manipulating the database that affect how subgraph data is stored, and can help query performance. Those items include:

* custom indexes (multicolumn indexes or partial indexes)
* creation of default attribute indexes (a lot of them are never used)
* account-like optimization
* statistics target

An example of what that could like like in YAML form is
```yaml
# Sketch of what an index definition file could look like. The file will
# contain many entries like this one
- rule: Messari analytics subgraphs
  match:
    # All subgraphs whose name matches this regex will be treated according
    # to these actions
    name: messari/.*
  actions:
    - entity:
        name: LiquidityPoolSnapshot
        index:
          - on: [pool, timestamp]
    - entity:
        name: LiquidityPool
        # Turn off attribute indexes
        default_indexes: false
        # Set the table to account-like
        account-like: true
        # Increase the statistics target
        stats-target: 300
        # Create some custom indexes
        index:
          # Use a GiST index since we use block_range
          - on: [block_range, timestamp, id]
            method: gist
          # A partial index that only covers blocks after a certain point
          # TODO: since the block number means different things on
          # different networks, we should either use a timespan or let users
          # match on network
          - on: [timestamp, id]
            after: 15664000
          - on: [pool_address, block_range, timestamp]
            method: gist
```

We need to think more about the way in which operators interact with these rules. Changing rules should not require a restart of `graph-node`. It should also be possible to list rules, delete them etc. Rules should be applied when a subgraph is deployed, but there should also be tooling to apply a new rule to an existing deployment.
