### ISSUE TITLE
Unable to index tenderly fork

### ISSUE THREAD

**Issue by skyao2002** [graphprotocol/graph-node#4356]
Report a Bug

**What is the current behavior?**

I get the following warnings when trying to index tenderly fork rpc:

```
graph-node_1  | Feb 12 08:52:45.676 WARN Trying again after eth_getLogs RPC call for block range: [16177264..16178721] failed (attempt #10) with result Err(Transport(Code(400))), sgd: 1, subgraph_id: Qmb1Ase7uK7oe66fUDPvEpexUL42zoFaPA4cyLyvEw9LEA, component: BlockStream
graph-node_1  | Feb 12 08:52:45.676 WARN Unexpected RPC error, error: Transport(Code(400)), sgd: 1, subgraph_id: Qmb1Ase7uK7oe66fUDPvEpexUL42zoFaPA4cyLyvEw9LEA, component: BlockStream
```

The indexing goes really slowly or not at all, I have waited an entire day and it still had not indexed 100 blocks.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I start a graph node using docker-compose and the following docker-compose.yaml

```
version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - 172.23.0.1:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:https://rpc.tenderly.co/fork/53fea442-6f5a-4c23-9a03-918f0db9c824'
      GRAPH_LOG: info
      ETHEREUM_REORG_THRESHOLD: 1
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
```

**What is the expected behavior?**

Expected behavior is to index the rpc correctly.
