### ISSUE TITLE
Graph Node Docker image can't connect to Postgres image.

### ISSUE THREAD

**Issue by firattale** [graphprotocol/graph-node#4467]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
The latest graph-node docker image can't connect to postgres image.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
this is the docker file I am trying to run.
```
#https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml
version: "3"
services:
    graph-node:
        image: graphprotocol/graph-node
        ports:
            - "8000:8000"
            - "8001:8001"
            - "8020:8020"
            - "8030:8030"
            - "8040:8040"
        depends_on:
            - ipfs
            - postgres
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            postgres_host: postgres
            postgres_user: graph-node
            postgres_pass: let-me-in
            postgres_db: graph-node
            ipfs: "ipfs:5001"
            ethereum: "mainnet:http://host.docker.internal:8545"
            GRAPH_LOG: info
            GRAPH_ALLOW_NON_DETERMINISTIC_IPFS: 1
    ipfs:
        image: ipfs/kubo:v0.15.0
        ports:
            - "5001:5001"
        #volumes:
        #  - ./data/ipfs:/data/ipfs
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
        environment:
            POSTGRES_USER: graph-node
            POSTGRES_PASSWORD: let-me-in
            POSTGRES_DB: graph-node
            PGDATA: "/data/postgres"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
```
<img width="1307" alt="Screen Shot 2023-03-17 at 10 45 05" src="https://user-images.githubusercontent.com/34514974/225870013-5d523535-e24a-45df-bdf7-881b19c85dd5.png">

Ipfs and postgres images run well, but graph-node creates problem while connecting to postgres.

```
subgraph-graph-node-1  | thread 'tokio-runtime-worker' panicked at 'Database does not use C locale. Please check the graph-node documentation for how to set up the database locale: database collation is `en_US.utf8` but must be `C`', store/postgres/src/connection_pool.rs:976:13
subgraph-graph-node-1  | Mar 17 09:38:42.216note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
subgraph-graph-node-1  |  CRIT Database does not use C locale. Please check the graph-node documentation for how to set up the database locale, error: database collation is `en_US.utf8` but must be `C`, pool: main, shard: primary, component: ConnectionPool
subgraph-graph-node-1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', /graph-node/store/postgres/src/connection_pool.rs:484:10
subgraph-graph-node-1 exited with code 101
```

An old version of the graph-node image works fine like 3178bb4. But the latest has this issue.

**What is the expected behavior?**
It should connect to postgres container as the old version does.
