### ISSUE TITLE
Configuration file and command line arguments

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#486]
Our CLI args so far have been added fairly ad-hoc. We'll want to clean these up a bit and expose everything in two ways: through a config file and through CLI args.

The config file would look something like this:
```toml
[ipfs]
node = "localhost:5001"

[ethereum]
network = "mainnet"
node = "https://mainnet.infura.io/"
block-chunk-size = 50

[ethereum.rpc]
max-parallel-requests = 2048
```

For all of these parameters, we'd have corresponding CLI arguments like
```
--ipfs-node localhost:5001
--ethereum-network mainnet
--ethereum-node https://mainnet.infura.io/
--ethereum-block-chunk-size 50
--ethereum-rpc-max-parallel-requests 2048
```
