### ISSUE TITLE
[Error - Question] Failed To get Entities from the store - Subgraph query error while trying to run graph-node and harhdat locally.

### ISSUE THREAD

**Issue by RafaDSan** [graphprotocol/graph-node#4871]
### Basic explanation of the problem
I'm currently working on a local subgraph for tracking events on an Ethereum smart contract. I aim to query specific entities, but I'm encountering an error when attempting to do so. The error message I'm receiving is: `'"message": "Failed to get entities from store: Odd number of digits, query = from \"sgd2\".\"task_created\"[*]{id = 1} order none first 100 at 0 query_id 7316f7c8141c25f5-6dc8c4ef99f8cc6a"'" `. I am honestly pretty noob on this, so I would greatly appreciate your help.

### Steps to reproduce the problem

1. Started a local blockchain with `npx hardhat node --hostname 0.0.0.0` 

2. Configured my `hardhat.config.ts` as follows:

     **localhost: {
     chainId: 1337,
      url: "htpp://0.0.0.0:8545"** 

3. Compiled my smart contract and deployed it to the hardhat node, which generated the following message: 

**Contract deployment: Web3Task
  Contract address:    0xec20dcbf0380f1c9856ee345af41f62ee45a95a1
  Transaction:         0xf8f0de6b1a4a2895dffc30db1f7dc56853c1b94570190ea43e2aa331b9dd3214
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  Value:               0 ETH
  Gas used:            4006332 of 4006332
  Block #38359529:     0x50ae5ffd41dee3d39dbc32ae9d5fcc95fac9830d2d7d1700795977e7027305ef**

4. I cloned the graph-node repository inside my main contracts directory

5. in `docker/docker-compose.yml` I configured the file as follows:

**version: "3"
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "mainnet:http://host.docker.internal:8545"
      GRAPH_LOG: info
      ETHEREUM_REORG_THRESHOLD: 1
      ETHEREUM_ANCESTOR_COUNT: 1
  ipfs:
    image: ipfs/kubo:v0.14.0
    ports:
      - "5001:5001"
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200",
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data**

6. Run the command `docker-compose up` (log in Relevant log output) 

7. And the hardhat log keeps going with the same values in a loop.

**eth_getBlockByNumber
eth_getBlockByHash
eth_getBlockByNumber (2)
eth_getLogs
eth_getBlockByHash
eth_getBlockByNumber (2)**

8. And then I upload my subgraph with:
`npm run create-local`
`npm run deploy-local`

which shows:
**Build completed: QmS2ppDqbW1Lg3B2DSkd8nK51vepDgdwsuCFg7vKufntHY

Deployed to http://localhost:8000/subgraphs/name/web3task_subraph/graphql

Subgraph endpoints:
Queries (HTTP):     http://localhost:8000/subgraphs/name/web3task_subraph**

9.  My schema.graphql looks as follows: (this is not the whole file, I just kept some of the events in order to not make it so long)

```
type TaskCreated @entity(immutable: true) {
  id: Bytes!
  taskId: BigInt! # uint256
  creator: Bytes! # address
  assignee: Bytes! # address
  reward: BigInt! # uint256
  endDate: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type TaskStarted @entity(immutable: true) {
  id: Bytes!
  taskId: BigInt! # uint256
  assignee: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}


```

**10. And then my query and the error:**

![image](https://github.com/graphprotocol/graph-node/assets/102108966/f6b20790-8aa4-4dda-9852-3d966689ab04)

I tried to run some local tests to generate traffic to query it. 

How do I solve this error and what is causing it?

Edit:

My subgraph.yaml:

```
specVersion: 0.0.5
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: Web3Task
    network: mainnet
    source:
      address: "0xec20dcbf0380f1c9856ee345af41f62ee45a95a1"
      abi: Web3Task
      startBlock: 1
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Approval
        - ApprovalForAll
        - AuthorizedOperator
        - AuthorizedPersonnel
        - TaskCreated
        - TaskStarted
        - TaskUpdated
        - Transfer
      abis:
        - name: Web3Task
          file: ./abis/Web3Task.json
      eventHandlers:
        - event: Approval(indexed address,indexed address,indexed uint256)
          handler: handleApproval
        - event: ApprovalForAll(indexed address,indexed address,bool)
          handler: handleApprovalForAll
        - event: AuthorizedOperator(indexed uint256,indexed bytes4)
          handler: handleAuthorizedOperator
        - event: AuthorizedPersonnel(indexed uint256,indexed address,bool)
          handler: handleAuthorizedPersonnel
        - event: TaskCreated(indexed uint256,indexed address,indexed address,uint256,uint256)
          handler: handleTaskCreated
        - event: TaskStarted(indexed uint256,indexed address)
          handler: handleTaskStarted
        - event: TaskUpdated(indexed uint256,uint8)
          handler: handleTaskUpdated
        - event: Transfer(indexed address,indexed address,indexed uint256)
          handler: handleTransfer
      file: ./src/web-3-task.ts
```

### Relevant log output

```Shell
graph-node_1  | Sep 15 16:18:49.114 INFO Scanning blocks [2133112, 2135111], range_size: 2000, sgd: 2, subgraph_id: QmS2ppDqbW1Lg3B2DSkd8nK51vepDgdwsuCFg7vKufntHY, component: BlockStream
graph-node_1  | Sep 15 16:18:49.482 INFO Scanning blocks [2135112, 2137111], range_size: 2000, sgd: 2, subgraph_id: QmS2ppDqbW1Lg3B2DSkd8nK51vepDgdwsuCFg7vKufntHY, component: BlockStream
graph-node_1  | Sep 15 16:18:49.815 INFO Scanning blocks [2137112, 2139111], range_size: 2000, sgd: 2, subgraph_id: QmS2ppDqbW1Lg3B2DSkd8nK51vepDgdwsuCFg7vKufntHY, component: BlockStream
graph-node_1  | Sep 15 16:18:50.180 INFO Scanning blocks [2139112, 2141111], range_size: 2000, sgd: 2, subgraph_id: QmS2ppDqbW1Lg3B2DSkd8nK51vepDgdwsuCFg7vKufntHY, component: BlockStream
graph-node_1  | Sep 15 16:18:50.519 INFO Scanning blocks [2141112, 2143111], range_size: 2000, sgd: 2, subgraph_id: QmS2ppDqbW1Lg3B2DSkd8nK51vepDgdwsuCFg7vKufntHY, component: BlockStream
graph-node_1  | Sep 15 16:18:50.882 INFO Scanning blocks [2143112, 2145111], range_size: 2000, sgd: 2, subgraph_id: QmS2ppDqbW1Lg3B2DSkd8nK51vepDgdwsuCFg7vKufntHY, component: BlockStream
graph-node_1  | Sep 15 16:18:51.237 INFO Scanning blocks [2145112, 2147111], range_size: 2000, sgd: 2, subgraph_id: QmS2ppDqbW1Lg3B2DSkd8nK51vepDgdwsuCFg7vKufntHY, component: BlockStream
graph-node_1  | Sep 15 16:18:51.569 INFO Scanning blocks [2147112, 2149111], range_size: 2000, sgd: 2, subgraph_id: QmS2ppDqbW1Lg3B2DSkd8nK51vepDgdwsuCFg7vKufntHY, component: BlockStream
graph-node_1  | Sep 15 16:18:51.904 INFO Scanning blocks [2149112, 2151111], range_size: 2000, sgd: 2, subgraph_id: QmS2ppDqbW1Lg3B2DSkd8nK51vepDgdwsuCFg7vKufntHY, component: BlockStream
graph-node_1  | Sep 15 16:18:52.263 INFO Scanning blocks [2151112, 2153111], range_size: 2000, sgd: 2, subgraph_id: QmS2ppDqbW1Lg3B2DSkd8nK51vepDgdwsuCFg7vKufntHY, component: BlockStream
```

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None
