### ISSUE TITLE
[Bug] graph-node container allocates huge amount of memory and aborts

### ISSUE THREAD

**Issue by aminlatifi** [graphprotocol/graph-node#4878]
### Description

I tried to deploy an instance of subgraph on a local node to index Ethereum Classic events. The initial thought was that it would be working, but I faced issues.
Before anything, should mention that I ran a successful deployment of xdai on my local node.

I followed this steps:

1. Modified `./docker/docker-compose.yml` and set 
```yml
ethereum: 'etc:https://etc.rivet.link'
```
2. Ran the `docker-compose.yml`. 

3. Created a deployment config to index a contract in Ethereum Classic using https://github.com/Giveth/giveconomy-subgraph
```yml
specVersion: 0.0.4
description: Giveth Subgraph
schema:
  file: ./schema.graphql
dataSources:

  - kind: ethereum/contract
    name: 'BTCC'
    network: 'etc'
    source:
      address: '0xca413215abB99f983359e058dCbF732363B14ac6'
      abi: ERC20
      startBlock: 16432915
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      abis:
        - name: ERC20
          file: ./abis/ERC20.json
      entities:
        - TokenBalance
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./src/mappings/ERC20.ts

```
4. Tried to deploy the subgraph by this command
```sh
graph create --node http://localhost:8020/ giveth/etc
graph deploy --node http://localhost:8020 --ipfs http://localhost:5001  giveth/etc subgraph.etc-test.yaml
```
5. The graph-node container keeps allocating more memory
<img width="618" alt="image" src="https://github.com/graphprotocol/graph-node/assets/5684607/5cd70e9a-8325-4ac5-98c3-f42c0f4b6b17">

Finally, it exceeds the limit and fails with error:
```log
...
docker-graph-node-1  | Sep 19 11:33:17.122 INFO Done processing trigger, gas_used: 384211612, data_source: BTCC, handler: handleTransfer, total_ms: 74, transaction: 0xbc73…c85b, address: 0xca41…4ac6, signature: Transfer(indexed address,indexed address,uint256), sgd: 1, subgraph_id: QmWCtbWck9BDbHtGEu3uRbLZbj2DwweUX6cqsSXoxzhj7y, component: SubgraphInstanceManager
docker-graph-node-1  | Sep 19 11:33:17.203 INFO Done processing trigger, gas_used: 384211612, data_source: BTCC, handler: handleTransfer, total_ms: 80, transaction: 0xbc73…c85b, address: 0xca41…4ac6, signature: Transfer(indexed address,indexed address,uint256), sgd: 1, subgraph_id: QmWCtbWck9BDbHtGEu3uRbLZbj2DwweUX6cqsSXoxzhj7y, component: SubgraphInstanceManager
docker-graph-node-1  | Sep 19 11:33:17.410 INFO Done processing trigger, gas_used: 384211612, data_source: BTCC, handler: handleTransfer, total_ms: 201, transaction: 0xbc73…c85b, address: 0xca41…4ac6, signature: Transfer(indexed address,indexed address,uint256), sgd: 1, subgraph_id: QmWCtbWck9BDbHtGEu3uRbLZbj2DwweUX6cqsSXoxzhj7y, component: SubgraphInstanceManager
docker-graph-node-1 exited with code 137
```

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

macOS
