### ISSUE TITLE
[Bug] Missing ABI reported as non-deterministic error

### ISSUE THREAD

**Issue by Chipe1** [graphprotocol/graph-node#4928]
### Bug report

I tried deploying a graph with missing a ABI(ABI was added to just one data source but was used in handlers for other sources too) and the node was silently stuck in a block that needed this ABI. Upon inspecting the graph-node docker logs I saw the error `ERRO Subgraph failed with non-deterministic error: failed to process trigger: block #1877280 (0x9fc0…625a), transaction e4d73c7a0271f8efe2d44721ccdc4dbc78d7ee270ecda98f131959bfec9b69fb: Could not find ABI for contract "IERC721", try adding it to the 'abis' section of the subgraph manifest`. The node was still returning results and showing `"hasIndexingErrors": false` in _meta
Based on the docs for [failed subgraphs](https://thegraph.com/docs/en/operating-graph-node/#failed-subgraphs) missing ABI should be considered a "final" deterministic failures. From the docs:
> In some cases, the non-deterministic label is incorrect, and the subgraph will never overcome the error; such failures should be reported as issues on the Graph Node repository.

Hence reporting this issue. Using `graphprotocol/graph-node:v0.30.0`

### Relevant log output

```Shell
Oct 19 12:57:37.383 ERRO Subgraph failed with non-deterministic error: failed to process trigger: block #1877280 (0x9fc0…625a), transaction e4d73c7a0271f8efe2d44721ccdc4dbc78d7ee270ecda98f131959bfec9b69fb: Could not find ABI for contract "IERC721", try adding it to the 'abis' section of the subgraph manifest	wasm backtrace:	    0: 0x37b3 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall	    1: 0x3fb9 - <unknown>!src/fetch/erc721/fetchERC721Token	    2: 0x4632 - <unknown>!src/mappings/asksV1/handleAskCreated	, retry_delay_s: 1800, attempt: 6, sgd: 172, subgraph_id: QmRhxkAhYDEgwY9JcV7vyZDomtJcpaF2aXCBL6xm6PbEfj, component: SubgraphInstanceManager
```

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by incrypto32** [comment]
Have you deployed this on the hosted service? I cant seem to retrieve the manifest from IPFS to reproduce

**Comment by Chipe1** [comment]
@incrypto32 Thanks for looking into this. No, this subgraph was deployed on a self-hosted node running `graphprotocol/graph-node:v0.30.0` in docker, not on the hosted service. It's running on a different chain (Canto) that's not supported on the hosted service

**Comment by incrypto32** [comment]
Do you have any other deployments on mainnet or a different chain than Canto, that i can use to reproduce this error?
Does Canto have a public archive endpoint i can use to test this subgraph out?

**Comment by Chipe1** [comment]
Created a minimal reproducible example on subgraph studio https://thegraph.com/studio/subgraph/missing-abi-nondeter-bug-4928 (build: `QmQuo2q2dEU9J6qi7no7Pe6tTMD4t3beedRzSjyJt1GPc2`)
Not sure whether you can access the graph details, so here's the code:
  - package.json
```
  "name": "redacted",
  "license": "UNLICENSED",
  "scripts": {
    "codegen": "graph codegen",
    "build": "graph build",
    "test": "graph test"
  },
  "dependencies": {
    "@amxx/graphprotocol-utils": "^1.1.0",
    "@openzeppelin/contracts": "^5.0.0"
  },
  "devDependencies": {
    "@graphprotocol/graph-cli": "0.60.0",
    "@graphprotocol/graph-ts": "0.31.0",
    "matchstick-as": "0.5.0"
  }
}
```
  - subgraph.yaml
  ```
specVersion: 0.0.4
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: punks
    network: mainnet
    source:
      abi: Punks
      startBlock: 18434892
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Punk
      abis:
        - name: Punks
          file: ./abis/punks.json
        - name: IERC721
          file: node_modules/@openzeppelin/contracts/build/contracts/IERC721Metadata.json
      eventHandlers:
        - event: PunkTransfer(indexed address,indexed address,uint256)
          handler: handlePunkTransfer
      file: ./src/punks.ts
  - kind: ethereum
    name: beanz
    network: mainnet
    source:
      abi: Beanz
      startBlock: 18434892
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Bean
      abis:
        - name: Beanz
          file: ./abis/beanz.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,indexed uint256)
          handler: handleTransfer
      file: ./src/beanz.ts
  ```
  - schema.graphql
  ```
type Punk @entity {
  id: ID!
  name: String!
  number: BigInt!
  uri: String
}

type Bean @entity {
  id: ID!
  name: String!
  number: BigInt!
  uri: String
}
  ```
  - src/punks.ts
  ```
import { Address } from "@graphprotocol/graph-ts";
import {IERC721} from "../generated/punks/IERC721"
import {PunkTransfer} from "../generated/punks/Punks"
import {Punk} from "../generated/schema"

export function handlePunkTransfer(event: PunkTransfer): void {
  const punk = new Punk(event.params.punkIndex.toString());
  punk.name = `Punk - ${event.params.punkIndex.toString()}`;
  punk.number = event.params.punkIndex;

  const contract = IERC721.bind(Address.fromString("0x8821BeE2ba0dF28761AffF119D66390D594CD280"))
  const tryTokenUri = contract.try_tokenURI(event.params.punkIndex);
  if (!tryTokenUri.reverted) {
    punk.uri = tryTokenUri.value;
  }
  
  punk.save();
}
  ```
  - src/beanz.ts
  ```
import { Address } from "@graphprotocol/graph-ts";
import {IERC721} from "../generated/punks/IERC721"
import {Transfer} from "../generated/beanz/Beanz"
import { Bean } from "../generated/schema"

export function handleTransfer(event: Transfer): void {
  const bean = new Bean(event.params.tokenId.toString());
  bean.name = `Bean - ${event.params.tokenId.toString()}`;
  bean.number = event.params.tokenId;

  if ("get me an error") {
    const contract = IERC721.bind(Address.fromString("0x8821BeE2ba0dF28761AffF119D66390D594CD280"))
    const tryTokenUri = contract.try_tokenURI(event.params.tokenId);
    if (!tryTokenUri.reverted) {
      bean.uri = tryTokenUri.value;
    }
  }
  
  bean.save();
}
  ```
  ABI for [beanz](https://etherscan.io/address/0x306b1ea3ecdf94ab739f1910bbda052ed4a9f949#code) and [punks](https://etherscan.io/address/0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb#code)
  
The main difference between both datasources is that punks has `IERC721` referenced in the ABI section whereas beanz doesn't.
In `src/beanz.ts` see the following if condition in the line `if ("get me an error")`. When this is commented out(deployed with tag 0.0.3) it works, but then that condition is run (tagged 0.0.4) I see an error in subgraph studio 
<img width="1313" alt="image" src="https://github.com/graphprotocol/graph-node/assets/9821389/e749d494-8283-4ae2-85a8-4bf6f5511ab6">
But in the logs it is mentioned as a "non-deterministic" error and continues to retry indexing (Not sure what happened to attempt 2 🤷 )
<img width="1304" alt="image" src="https://github.com/graphprotocol/graph-node/assets/9821389/3cc53b14-3fc2-44ae-9a6e-1482df64c650">

Note that beanz.ts imports from the generated files for punks.
