### ISSUE TITLE
[Feature] Declarative eth calls

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#5262]
### Description

Subgraphs that use `ethereum.call` a lot can become extremely slow because of these calls; even when a subgraph makes a moderate amount of calls, the overhead of `eth_call` tends to dominate indexing time. Currently, `eth_calls` need to be executed serially, as they are embedded in the WASM code and `graph-node` does not know about these calls until handlers try to execute them.

It should therefore become possible to declare `eth_calls` ahead of time so that `graph-node` can execute them in parallel, and ideally as part of the indexing pipeline so that when handlers run, the results of the calls are known already. To that end, the manifest syntax should be extended. It should be possible to annotate handlers with `eth_calls` with the following syntax:

```yaml
      eventHandlers:
        - event: Swap(indexed address,indexed address,int256,int256,uint160,uint128,int24)
          handler: handleSwap
          calls:
            - global0X128: Pool[event.address].feeGrowthGlobal0X128()
            - global1X128: Pool[event.address].feeGrowthGlobal1X128()
```

With these declarations, the two calls will be executed before the handler is invoked. The declaration `global0X128` has the same effect as this code in the handler

```
let poolContract = PoolABI.bind(event.address)
let feeGrowthGlobal0X128 = poolContract.try_feeGrowthGlobal0X128()
```

Without a call declaration, this causes an actual `eth_call` (or a lookup from the call cache if we made this call before) With the call declaration, the above code will simply get the results from an in-memory cache that was populated before the handler ran.

Declared calls can access the `event.address` of the underlying event as well as all the `event.params`, so that a declared call could also look like
```yaml
calls:
  - ERC20DecimalsToken0: ERC20[event.params.token0].decimals()
```

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.
