### ISSUE TITLE
[Feature] Declarative Calls Feedback

### ISSUE THREAD

**Issue by melotik** [graphprotocol/graph-node#5445]
### Description

I spent some time trying to add declarative calls (https://github.com/graphprotocol/graph-node/pull/5264) to messari's compound v3 subgraph as it uses a lot of `eth_call`s. I wasn't able to fully test any of this yet due to this blocker (https://github.com/graphprotocol/graph-node/issues/5444), however I had some feedback or requests for use cases that showed up when I was working to cut over the subgraph to use declarative calls.

- Using an `eth_call` as input for another `eth_call`, here is a real example:
```typescript
const utilization = cometContract.getUtilization();
const borrowRate = cometContract.getBorrowRate(utilization).toBigDecimal();
const supplyRate = cometContract.getSupplyRate(utilization).toBigDecimal();
```
- Multiple calls on one handler for the same function call with different input:
```yaml
calls:
	Comet.totalsBasic: Comet[event.address].totalsBasic(event.params.liquidator)
	Come.totalsBasic: Comet[event.address].totalsBasic(event.params.borrower)
```
> Note: This may be possible to do already, but I am not sure 

### Are you aware of any blockers that must be resolved before implementing this feature? If so, which? Link to any relevant GitHub issues.

https://github.com/graphprotocol/graph-node/issues/5444

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by juanmardefago** [comment]
I've been playing a bit with declarative eth_calls too, and while doing so I also got into a similar situation, not entirely the same, but close.

Due to the limitations on what you can declare (only event.address or event.params.<x>), I couldn't get my refactor to work, since the value I want to use for the contract address part isn't in the event.address or the params, but rather as either a field in a particular entity at that moment in time, or (by doing some workarounds) as a hardcoded value).

I'm thinking it's virtually the same issue described here in the first bullet point, even if the value to be used isn't really a response from a previous contract, but rather a hardcoded value/value from an already existing entity.

**Comment by azf20** [comment]
Thanks both this is great feedback.
@lutter what do you think on the "dependent calls" case?
@juanmardefago can you share a link to the existing handler so we can take a look at the "entity field input" example?

**Comment by lutter** [comment]
It's already possible to have multiple calls on the same event handler. Just give it different labels, and that works; something like
```yaml
calls:
        totalsBasicLiquidator: Comet[event.address].totalsBasic(event.params.liquidator)
        totalsBasicBorrower: Comet[event.address].totalsBasic(event.params.borrower)
```

The things that are not supported yet are:
1. Using the result of one call as the input for another
2. Using a fixed value (`Contract['0xdeadbeef'].function()`)
3. Accessing more data than just the event, like entities from the database. This one might be pretty complicated. @juanmardefago could you sketch out in more detail what exactly you need to access there, like where does the id for the entity you need to look up come from?
