### ISSUE TITLE
Support parameterized Substreams modules from the subgraph.yaml manifest

### ISSUE THREAD

**Issue by abourget** [graphprotocol/graph-node#5451]
### Description

There is already support for applying params in https://github.com/graphprotocol/graph-node/pull/4759/files
but I'm not sure it's exposed to the end users. 

I see no reference to it in https://thegraph.com/docs/en/cookbook/substreams-powered-subgraphs/#defining-a-substreams-package and I've been told that it was used internally, but not exposed externally by @mangas 

With all the efforts to simplify using Substreams, it would be an incredible addition that we can use some well-known (we're calling them Foundational) modules can be reused, and provide a semantic for querying the chain's data, using indexes to skip lots of blocks, etc..

```yaml
dataSources:
  - kind: substreams
    name: Transaction
    network: mainnet
    source:
      package:
        moduleName: map_filter_transactions
        file: ethereum-explorer-v0.1.2.spkg
        params:
          map_super_bob: "this is a nice params string"
          "ethcommon:map_filter_logs": "this is a great params string
# the previous version is how params are laid out in `substreams.yaml`, a little more terse, but some might dislike the quotes around imported modules, so
# alternatively:
        params:
          - module: map_super_bob
            value: "this is a nice params string"
          - module: ethcommon:map_filter_logs
            value: "(contract:0x23123123123)"

  ```

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.
