### ISSUE TITLE
[Bug] Declaractive Calls And Structs

### ISSUE THREAD

**Issue by Data-Nexus** [graphprotocol/graph-node#6059]
### Bug report

If an event emits a struct, and I attempt to use this in the declaractive call, it says the struct is not an address rather than selecting just the address.

e.g.
```
- event: AssetChanged((uint8,address,uint256),uint256)
  handler: handleAssetChanged
  calls:
    assetHairCutChangedName: ERC20[event.params.asset.addr].name()
```
Rather than selecting the address from the `(uint8,address,uint256)` struct, it says the struct is not an address.

Simply removing the declaractive call allowed the subgraph to progress, but it was a bit tricky to troubleshoot because the error logs didn't list an event handler etc. 

### Relevant log output

```Shell

```

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [x] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Windows
